version: "3.8"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      PORT: "3000"
      MONGO_URI: ""
      JWT_SECRET_KEY: ""
      ADMIN_SECRET_KEY: ""
      AWS_REGION: ""
      AWS_ACCESS_KEY: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_S3_ASSETS_BUCKET: ""
      USER_FRONTEND_URL: ""
      ADMIN_FRONTEND_URL: ""
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
